=== esraa237/ITI_labs/Xml/Day3/task3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="library">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Location">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Country" type="xs:string"/>
							<xs:element name="Governorate" type="xs:string"/>
							<xs:element name="City" type="xs:string"/>
							<xs:element name="Street" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Description" type="xs:string"/>
				<xs:element name="Librarian">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string"/>
						<xs:attribute name="phone" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="books">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="book" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Preface" type="xs:string"/>
										<xs:element name="parts">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="part" minOccurs="1" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="chapters">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="chapter" minOccurs="1" maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="summary" type="xs:string"/>
																						<xs:element name="sections">
																							<xs:complexType>
																								<xs:sequence>
																									<xs:element name="section" minOccurs="1" maxOccurs="unbounded">
																										<xs:complexType>
																											<xs:sequence>
																												<xs:element name="content" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
																											</xs:sequence>
																										</xs:complexType>
																									</xs:element>
																								</xs:sequence>
																							</xs:complexType>
																						</xs:element>
																					</xs:sequence>
																					<xs:attribute name="title" type="xs:string" use="optional"/>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute name="title" type="xs:string" use="required"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="ISBN" type="xs:ID" use="required"/>
									<xs:attribute name="Author" type="xs:string" use="required"/>
									<xs:attribute name="title" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== esraa237/ITI_labs/Xml/Day1/task1.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="G:\ITI Labs\Xml\Day3\task3.xsd">
	<Location>
		<Country>Egypt</Country>
		<Governorate>Cairo</Governorate>
		<City>Nasr City</City>
		<Street>123 Library Street</Street>
	</Location>
	<Description><![CDATA[(This library offers a wide variety of books in different genres and provides a quiet study environment. & have many books)]]></Description>
	<Librarian name="Omar Hassan" phone="+201234567890"/>
	<books>
		<!-- First Book -->
		<book ISBN="A1" Author="Taha Hussein" title="the days">
			<Preface><![CDATA[An autobiography by Taha Hussein & detailing his life journey from childhood to adulthood.]]></Preface>
			<parts>
				<part title="Childhood">
					<chapters>
						<chapter title="The Beginning">
							<summary>Taha Hussein’s childhood and upbringing in a small Egyptian village.</summary>
							<sections>
								<section>
									<content>Taha Hussein reflects on his early life, his village memories, and his love for learning from a young age</content>
									<content>Taha Hussein reflects on his early life, his village memories, and his love for learning from a young age.</content>
									<content>Taha Hussein reflects on his early life, his village memories, and his love for learning from a young age</content>
								</section>
								<section>
									<content>Details of Taha Hussein losing his sight and how it shaped his character and resilience.</content>
								</section>
							</sections>
						</chapter>
						<chapter title="The Quest for Knowledge">
							<summary>The beginning of Taha Hussein’s educational journey and his move to Cairo.</summary>
							<sections>
								<section>
									<content>Attending Al-Azhar University was a pivotal chapter in Taha Hussein’s life.</content>
								</section>
								<section>
									<content>How Taha Hussein moved from traditional education to attending the modern university.</content>
								</section>
							</sections>
						</chapter>
					</chapters>
				</part>
			</parts>
		</book>
		<!--second book-->
		<book ISBN="A2" Author="Taha Hussein" title="the days">
			<Preface><![CDATA[An autobiography by Taha Hussein & detailing his life journey from childhood to adulthood.]]></Preface>
			<parts>
				<part title="Childhood">
					<chapters>
						<chapter title="The Beginning">
							<summary>Taha Hussein’s childhood and upbringing in a small Egyptian village.</summary>
							<sections>
								<section>
									<content>Taha Hussein reflects on his early life, his village memories, and his love for learning from a young age</content>
									<content>Taha Hussein reflects on his early life, his village memories, and his love for learning from a young age.</content>
									<content>Taha Hussein reflects on his early life, his village memories, and his love for learning from a young age</content>
								</section>
								<section>
									<content>Details of Taha Hussein losing his sight and how it shaped his character and resilience.</content>
								</section>
							</sections>
						</chapter>
						<chapter title="The Quest for Knowledge">
							<summary>The beginning of Taha Hussein’s educational journey and his move to Cairo.</summary>
							<sections>
								<section>
									<content>Attending Al-Azhar University was a pivotal chapter in Taha Hussein’s life.</content>
								</section>
								<section>
									<content>How Taha Hussein moved from traditional education to attending the modern university.</content>
								</section>
							</sections>
						</chapter>
					</chapters>
				</part>
			</parts>
		</book>
	</books>
</library>
